create table abstract_entity
(
    dtype       text  not null,
    id          bigint generated by default as identity
        constraint abstract_entity_pk
            primary key,
    entity_data jsonb not null
);

insert into abstract_entity (dtype, entity_data)
values ('EntityA', '{
    "testA": "Test Test",
    "id": 999
}');